addict==2.4.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
async-timeout==4.0.2
asynctest==0.13.0
attrs==23.1.0
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4==4.12.2
bleach==6.0.0
-e git+https://github.com/DLR-RM/BlenderProc.git@bff4136f3b8e4bbe7929f2611c8d8f10d0b203a1#egg=blenderproc
bokeh==1.4.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama==0.4.3
ConfigArgParse==1.5.3
-e git+ssh://git@github.com/garyraise/cosypose.git@fb5d3fb1629d01610690077c2a0a48942a76dfc9#egg=cosypose&subdirectory=../../cosypose
cycler==0.11.0
Cython==0.29.21
cytoolz==0.11.0
dash==2.9.3
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1644602974678/work
dask-jobqueue @ file:///home/conda/feedstock_root/build_artifacts/dask-jobqueue_1657781391231/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml==0.7.1
deprecation==2.1.0
distributed==2.9.1
docker-pycreds==0.4.0
fastjsonschema==2.16.3
Flask==2.2.5
frozenlist==1.3.3
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1674184942191/work
gitdb==4.0.10
GitPython==3.1.31
glumpy==1.2.0
h5py==3.8.0
HeapDict==1.0.1
idna==3.4
imageio==2.6.1
importlib-metadata==6.6.0
importlib-resources==5.12.0
ipdb==0.12.3
ipykernel==5.1.3
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1651240553635/work
ipython-genutils==0.2.0
ipywidgets==8.0.6
itsdangerous==2.1.2
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2==3.0.0
job-runner==0.0.1
joblib==0.14.1
json5==0.9.11
jsonpatch==1.32
jsonpointer==2.3
jsonschema==4.17.3
jupyter-client==5.3.4
jupyter-server==1.24.0
jupyter-server-proxy==1.5.0
jupyter_core==4.12.0
jupyter_packaging==0.12.3
jupyterlab==1.2.4
jupyterlab-pygments==0.2.2
jupyterlab-server==1.0.6
jupyterlab-widgets==3.0.7
kiwisolver==1.4.4
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lxml==4.4.2
MarkupSafe==2.1.2
matplotlib==3.1.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mistune==2.0.5
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1605895130094/work
multidict==6.0.4
nbclassic==1.0.0
nbclient==0.7.4
nbconvert==7.3.1
nbformat==5.7.0
nest-asyncio==1.5.6
networkx==2.6.3
notebook==6.5.4
notebook_shim==0.2.3
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1604945996409/work
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
open3d==0.17.0
opencv-contrib-python==4.4.0.42
opencv-python==4.1.2.30
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==1.3.5
pandocfilters==1.5.0
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
pathtools==0.1.2
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==9.5.0
pkgutil_resolve_name==1.3.10
plotly==5.14.1
plyfile==0.7.1
progressbar==2.5
prometheus-client==0.16.0
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
protobuf==4.22.4
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1603570991184/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyarrow==12.0.0
pybullet==3.2.5
pycollada==0.6
pycparser==2.21
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
PyOpenGL==3.1.0
pyparsing==3.0.9
pypng==0.0.20
pyquaternion==0.9.9
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2023.3
PyWavefront==1.3.1
PyWavelets==1.3.0
PyYAML==5.3.1
pyzmq==25.0.2
requests==2.30.0
scikit-image==0.16.2
scikit-learn==0.22.1
scikit-video==1.1.11
scipy==1.4.1
seaborn==0.12.2
Send2Trash==1.8.2
sentry-sdk==1.22.1
setproctitle==1.3.2
Shapely==1.7.0
simpervisor==0.4
simplejson==3.17.0
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve==2.4.1
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tenacity==8.2.2
terminado==0.17.1
tinycss2==1.2.1
tomlkit==0.11.8
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==1.13.1
torchnet==0.0.4
torchvision==0.14.1
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1604105014127/work
tqdm==4.41.1
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
transforms3d==0.3.1
triangle==20220202
trimesh==3.5.16
typing_extensions==4.5.0
urllib3==1.26.15
visdom==0.2.4
wandb==0.15.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webencodings==0.5.1
websocket-client==1.5.1
Werkzeug==2.2.3
wget==3.2
widgetsnbextension==4.0.7
xarray==0.14.1
yarl==1.9.2
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1651156074437/work
zipp==3.15.0
