name: cosypose
channels:
   - conda-forge
   - pytorch
   - robostack-staging
dependencies:
  - ros-noetic-desktop
  - python
  - pinocchio
  - urdfdom
  - assimp
  - rclone
  - gxx_linux-64
  - git-lfs
  - ffmpeg
  - bzip2
  - git
  - cmake
  - pip
  - numpy
  - pillow
  - ipython
  - pip:
      - torch
      - torchvision
      - pybullet
      - imageio
      - simplejson
      - open3d
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - distributed
      - joblib
      - pandas
      - xarray
      - pyarrow
      - matplotlib
      - jinja2
      - bokeh
      - plyfile
      - trimesh
      - pycollada
      - shapely
      - wget
      - pypng
      - PyOpenGL
      - Cython
      - glumpy
      - ipdb
      - colorama
      - scikit-video
      - scikit-image
      - scikit-learn
      - pyyaml
      - ipykernel
      - scipy
      - pywavefront
      - jupyter-client
      - jupyter-core
      - jupyter-server-proxy
      - jupyterlab
      - jupyterlab-server
